#!/bin/bash

set -e

conf () {
  HIVE_CONF_DIR="${HIVE_HOME}/generated-conf"
  mkdir -p "${HIVE_HOME}/conf"
  mkdir -p "${HIVE_CONF_DIR}"
  cp ${HIVE_HOME}/conf/* ${HIVE_CONF_DIR}/

  if [[ -v EXTRA_CONFIG_YAML_PATH ]]; then
    PROPERTIES=""
    while read line; do
      IFS=: read -r key val <<< $line
      PROPERTIES="${PROPERTIES}  <property>\n    <name>${key}</name>\n    <value>${val}</value>\n  </property>\n"
    done <"${EXTRA_CONFIG_YAML_PATH}"

    echo "${PROPERTIES}"

    sed -i "/<\/configuration>/i ${PROPERTIES}" ${HIVE_CONF_DIR}/metastore-site.xml
  fi

  if [[ -v POSTGRES_PASSWORD ]]; then
    PROPERTIES="  <property>\n    <name>javax.jdo.option.ConnectionPassword</name>\n    <value>${POSTGRES_PASSWORD}</value>\n  </property>\n"
    sed -i "/<\/configuration>/i ${PROPERTIES}" ${HIVE_CONF_DIR}/metastore-site.xml
  fi
}

start () {
  exec env "HIVE_CONF_DIR=${HIVE_CONF_DIR}" "${HIVE_HOME}/bin/start-metastore" "${@:2}"
}

migrate () {
  exec "${HIVE_HOME}/bin/schematool" -initSchema -dbType postgres || true
}

conf
if [ "$1" == "start" ]; then
  start
elif [ "$1" == "migrate" ]; then
  migrate
else 
  echo "Available commands: start / migrate"
fi
