image:
  repository: 
  tag:
resources: {}
nodeSelector:
serviceAccount: 
  create: false
  annotations: {}
podAnnotations:
externalPostgresql:
  enabled: false
  host: 
  port:
  auth:
    username: hive
    database: metastore
    password:
postgresql:
  enabled: true
  auth:
    username: hive
    database: metastore
    password: metastore
  primary:
    nodeSelector: {}
    persistence:
      enabled: true
      size: 8Gi
heapsize: 2048
extraConfigYamlPath: 
s3:
  accessKey:
  secretKey:
  credentialsProvider: com.amazonaws.auth.DefaultAWSCredentialsProviderChain

