image:
  repository: 
  tag:
resources: {}
nodeSelector:
serviceAccount: 
  create: false
  annotations: {}
podAnnotations:
externalPostgresql:
  host: 
  port:
  auth:
    database:
    username:
    existingSecret:
    secretKeys:
      userPasswordKey:
  #*auth:
  # username: hive
  # database: metastore
  # password:*/
postgresql:
  enabled: true
  auth:
    username: hive
    database: metastore
    password: metastore
    existingSecret:
    secretKeys:
      userPasswordKey:
  primary:
    nodeSelector: {}
    persistence:
      enabled: true
      size: 8Gi
heapsize: 2048
extraConfigYamlPath: 
s3:
  accessKey:
  secretKey:
  credentialsProvider: com.amazonaws.auth.DefaultAWSCredentialsProviderChain
